checks:
  javascript: true
filter:
  excluded_paths:
    - node_modules/*

build:
  cache:
    disabled: true

  environment:
    google_chrome:
      use_latest: true


  dependencies:
    before:
      - export LATEST=$(nvm ls-remote | tail -1)
      - nvm install $LATEST
#      - nvm use $LATEST
      - npm install grunt-cli -g
      - npm install
      - node_modules/protractor/bin/webdriver-manager update

  tests:
    override:
      -
        command: 'grunt coverage'
        coverage:
          file: 'build/coverage/clover.xml'
          format: 'clover'
